### ISSUE TITLE
Make Place Codable

### ISSUE THREAD

**Issue by 0xifarouk** [fpseverino/apple-maps-kit#1]
Hi there, 

Can we make `Place` and the other types `Codable` so we can return them directly as JSON via HB or Vapor?

**Comment by 0xifarouk** [comment]
I made a PR:
https://github.com/fpseverino/apple-maps-kit/pull/2

**Comment by fpseverino** [comment]
Absolutely, thanks for the PR!

Although I might suggest sanitizing the objects returned by the API, as some may have useless or not well organized information, and doing it on the server instead of the client, as moving load from the client to the server is exactly the point of the Apple Maps Server API

**Comment by 0xifarouk** [comment]
Yes I totally agree, but also there is no harm making to Codable so the user can decide which approach to take.
